# Numpy 

Numpy is a linear algebra of python library, its incredibly fast , for linear Algebra and has building lies in C programming , numpy arrays comes in two form either VECTORS OR MATRIXES.
Vectors are one dimensional arrays while Matrixes is 2- dimensional arrays, but note that matrix can still have one row and one columns 

Numpy Arrays: 
    they are the ways we use numpy in python , its comes essentuially with two flavours in python, which can be 1 dimensional arrays or vectors , 
    or 2 dimensional arrays or matrixes 

In [2]:
#creating numpy array in a list 
import numpy as np 
myList = [1, 2, 3,]    #casting it in 1 demsional array 
arr= np.array(myList)

In [5]:
#returning 1 dimensional array  
arr

array([1, 2, 3])

In [11]:
#casting list of list 
myMath = [[1, 2, 3],[4, 5, 6,],[7, 8, 9]]

In [12]:
myMath

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
#casting it into two dimensional array 3 rows and 3 columns  
myArr = np.array(myMath)

myArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
#generating even numbers arrays using numpy , third arguments takes number of steps you want 
evenNos = np.arange(0, 20, 2)

In [16]:
evenNos

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
evenMat = np.array(evenNos)

In [19]:
evenMat

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
#generating arrays of all zeors 
zerosArr= np.zeros(5)

In [21]:
zerosArr

array([0., 0., 0., 0., 0.])

In [24]:
zerosArrs2 = np.zeros((5, 5))
zerosArrs2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
zerosArr3= np.zeros((2, 3))

In [26]:
zerosArr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
onesArr = np.ones((4, 5))

In [29]:
onesArr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
#genrating using linspace, showimg third argument has nos of spaces you wanted 
linNos = np.linspace(0, 5, 10)

In [32]:
linNos

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [33]:
#returning 100 evenly space 1dimenstional array 
linNos1 = np.linspace(0, 5, 100)

In [34]:
linNos1

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [36]:
#eye , is used to in linear algebra, 1 diagonal is making it 1
Lin = np.eye(5)

In [37]:
Lin

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
#genrating random numbers 
np.random.rand(5)

array([0.58719464, 0.81276342, 0.00625287, 0.83780061, 0.63633074])

In [39]:
#returning random numbers that are around normal standard distributions 
np.random.randn(5)

array([-1.20927703, -0.76530621, -0.22394422,  2.02883633, -0.14587737])

In [40]:
np.random.randn(4,4)

array([[-1.03556343,  0.69896865,  1.3562664 , -1.11012424],
       [-0.97131127,  1.69528408,  0.16613566, -2.16611025],
       [ 0.36073796,  0.42415422, -0.19816336,  0.48829346],
       [-0.28598443, -2.39637007, -1.22215667,  1.91271962]])

In [43]:
#genrating random distribution for an integer 
np.random.randint(1, 100, 10)

array([27, 77,  7, 88,  2, 97, 13, 80, 73, 88])

In [44]:
np.random.randint(0, 10)

5

In [45]:
np.random.randint(0, 10, 2)

array([6, 0])

In [52]:
#checking application of random intergers array in 1 dimensional array 
arr = np.arange(25)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [57]:
raarra = np.random.randint(0, 50, 10)

In [58]:
raarra

array([14,  9, 23, 27, 36, 38, 31, 17, 16, 49])

In [59]:
#reshaping an array by passing the numbers of rows and columns you want 
reshapeArr = arr.reshape(5,5 )

In [60]:
reshapeArr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [61]:
#checking for the max values in the array 
raarra.max()

49

In [63]:
#checking for minumum values of the array 
raarra.min()

9

In [65]:
#rechecking the array, checking for the psoition of minimum and maximum value  
raarra

array([14,  9, 23, 27, 36, 38, 31, 17, 16, 49])

In [66]:
#returning the index location of max values 
raarra.argmax()

9

In [68]:
#returning the index location of minimum values 
raarra.argmin()

1

In [72]:
#if you wanna firgure out the shape of a vector 
myArr.shape

(3, 3)

In [73]:
arr.shape

(25,)

In [75]:
#reshaping arr to 5dimensuional array 
arrRe= arr.reshape(5,5)

In [76]:
arrRe

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [78]:
arrRe.shape

(5, 5)

In [79]:
#checking for dtypes we have in an array
arr.dtype

dtype('int32')

In [81]:
from random import randint 
randint(2, 10)

2

# indexinga nd selection for numpy arrays 

In [86]:
import numpy as np 

#creating a sample array
arr = np.arange (0, 11)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
#calling a value through index in numpy 
arr[8]

8

In [90]:
#calling muplity values through indexing 
arr[3:6]

array([3, 4, 5])

In [91]:
arr[1:5]

array([1, 2, 3, 4])

In [92]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [93]:
arr[:6]  #grabbing everything before index 6

array([0, 1, 2, 3, 4, 5])

In [94]:
arr[5:]  #grabing everything beyond index 5

array([ 5,  6,  7,  8,  9, 10])

numpy array is different from normal python list bcous its has the ability to broadcast  

In [137]:
arr[1:5] = 100

In [138]:
arr

array([ 99, 100, 100, 100, 100,  99,   6,   7,   8,   9,  10])

In [106]:
arr= np.arange(0, 11)

In [114]:
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [115]:
#showing imporatnt note on slices of an array 
slicesOfArray = arr[0:6]


In [116]:
slicesOfArray

array([  0, 100, 100, 100, 100,   5])

In [118]:
#TYRYING TO BROADCAST SLICES OF ARRAY 
slicesOfArray[:] = 99

In [119]:
slicesOfArray

array([99, 99, 99, 99, 99, 99])

In [120]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [121]:
#to specifically copy an arr in a range of numbers in an array 
arrCopy = arr.copy()

In [122]:
arrCopy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [124]:
#changing array copy by broadcasting 100 into array 
arrCopy[:] = 100

In [126]:
arrCopy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [127]:
#original array is still unaffecting by the broadcating 
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Indexing a 2 dimensional array 

In [134]:
#creating a 2 dimensional arrray 
arr_2d = np.array([[5, 8, 10], [15, 18, 20], [25, 28, 30]])

In [135]:
arr_2d

array([[ 5,  8, 10],
       [15, 18, 20],
       [25, 28, 30]])

#two ways of grabbing and array from 2 dimensional array , 
double [] format and single [] format 

In [139]:
arr_2d

array([[ 5,  8, 10],
       [15, 18, 20],
       [25, 28, 30]])

In [140]:
arr_2d[0, 0]    #first 0 indicate row why second indicate column 

5

In [141]:
#or its can be 
arr_2d[0][0]

5

In [142]:
#indexing the entire row back 
arr_2d[0]

array([ 5,  8, 10])

In [143]:
#grabbing 18 
arr_2d[1][1]

18

In [144]:
#grabbing 15
arr_2d[1][0]

15

In [146]:
#grabbing 20
arr_2d[1][2]

20

In [147]:
#grabbing 25
arr_2d[2][0]

25

In [148]:
#grabbing 28
arr_2d[2][1]

28

In [150]:
#grabbing 30 
arr_2d[2][2]

30

In [152]:
#grabbing more than one in the matrix 
arr_2d[:2, 1:]

array([[ 8, 10],
       [18, 20]])

In [154]:
arr_2d[:1, 0:]

array([[ 5,  8, 10]])

In [157]:
arr_2d[:2, 0:]

array([[ 5,  8, 10],
       [15, 18, 20]])

In [158]:
arr =np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
#comparism of an array 
boolArr = arr>5

In [161]:
boolArr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [162]:
arr[boolArr]

array([ 6,  7,  8,  9, 10])

In [163]:
arr[arr > 5]  #syntax used in conditional selections 

array([ 6,  7,  8,  9, 10])

In [164]:
#knowing all the array that are less than 3 
arr[arr< 3]

array([1, 2])

In [167]:
#creating a new 2d array 
arr_2d = np.arange(50).reshape(5, 10)

In [168]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [172]:
#grabbing from 2d array 
arr_2d[0, 5]

5

In [175]:
arr_2d[1:3, 3:5 ]

array([[13, 14],
       [23, 24]])

In [176]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# NUMPY OPERATIONS 

Array with Array
Array with scalar 
universal Array Functions 

In [178]:
import numpy as np 
arr = np.arange (0, 11)

In [179]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [180]:
#adding two arrays together based on element by element 
additionArray = arr + arr

In [182]:
additionArray

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [183]:
#subracting two arrays based on element by element  
subractingArray = arr - arr 

In [184]:
subractingArray

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [185]:
#multiplying two arrays together 
multiplyArray = arr * arr

In [187]:
multiplyArray

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [189]:
#performing operation in arrat with scalar entity 
#adding 100 to every element in the array 
adding100 = arr + 100

In [190]:
adding100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [191]:
 #muplyting 100 to every element 
multiply100 = arr * 100 
multiply100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [192]:
#subracting 100 from every element 
subract100 = arr - 100
subract100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [194]:
#common error numpy will issues 
1/0 

ZeroDivisionError: division by zero

In [195]:
#other warning numpy will issues 
arr/arr 

C:\Users\HP\AppData\Local\Temp/ipykernel_8796/3068588409.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [197]:
#other warning issues by numpy 
1/arr 

C:\Users\HP\AppData\Local\Temp/ipykernel_8796/1990854363.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [198]:
#doing arrays with exponent 
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

Describing universal array functions 

In [200]:
squareArray = np.sqrt(arr)

In [202]:
squareArray

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [203]:
#taking the exponential of an array 
exponetArray = np.exp(arr)

In [204]:
exponetArray

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [205]:
#checking the maximun of array 
maxArray = np.max(arr)

In [206]:
maxArray

10

In [207]:
#checking the minimum array 
minArray = np.min(arr)

In [208]:
minArray

0

In [209]:
#passing sin in an array 
sinArray = np.sin(arr)

In [210]:
sinArray

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [211]:
#getting lorigthm of the array 
logArr = np.log(arr)

C:\Users\HP\AppData\Local\Temp/ipykernel_8796/150106484.py:2: RuntimeWarning: divide by zero encountered in log
  logArr = np.log(arr)


In [212]:
logArr

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])